In [ ]:
import numpy as np

# Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.
D = np.diag([1, 2, 3])

result = np.array(np.linalg.inv(D))
print(np.dot(D,result))
print(np.linalg.det(D))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
6.0


In [ ]:
# Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.
import random

up = np.triu(np.random.rand(3,3))
print(up)
print()
down = np.tril(up)
print(down)

[[0.38247276 0.41905672 0.4776305 ]
 [0.         0.71929004 0.21032215]
 [0.         0.         0.67859962]]

[[0.38247276 0.         0.        ]
 [0.         0.71929004 0.        ]
 [0.         0.         0.67859962]]


In [ ]:
# Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.
A = np.array([[4, 7], [2, 6]])

result = np.array(np.linalg.inv(A))
print(np.dot(A,result))
print(np.linalg.det(A))

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
10.000000000000002


In [27]:
import numpy as np
# Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.
# - 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
# - 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.
X = np.array([1, 2, 3])
para = np.arange(9).reshape(3,3)

Y = X.dot(para)
Y

array([24, 30, 36])

In [30]:
# Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.
# - 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
# - 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

X = np.array([1, 2, 3])
W = np.random.rand(3,3)

result = X.dot(W)
result


(3,)
(3, 3)


array([3.10526461, 3.89185651, 2.71531427])

In [32]:
# Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.
# - 1단계: 입력 벡터 X를 정의.
# - 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
# - 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산
# 활성화 함수 적용<br>
X = np.array([1, -2, 3])

W = np.random.rand(3,3)
b = np.random.rand(3)
Z = X.dot(W) + b

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(0, x)

output_relu = relu(Z)
output_sigmoid = sigmoid(Z)

print(output_relu)
print(output_sigmoid)

[0.         0.         0.21856382]
[0.48817763 0.46472372 0.55442447]


In [41]:
# Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여 x와 y를 구하세요.
# 3x + 4y = 10
# 2x + y = 5
# 1. 계수 행렬 A와 결과 벡터 b를 정의.
# 2. 행렬 A의 역행렬을 구한다.
# 3. 역행렬을 사용하여 변수 x를 구한다.

A = np.array([[3,4], [2,1]])
b = np.array([10,5])

reverse_A = np.linalg.inv(A)
print(reverse_A)

result = A @ reverse_A
print(result)

x = np.dot(reverse_A, b)
print(x)

[[-0.2  0.8]
 [ 0.4 -0.6]]
[[1. 0.]
 [0. 1.]]
[2. 1.]


In [48]:
# Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.
# 원래 점의 좌표 p와 변환 행렬 T 정의
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])

# 1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
# 2. 변환 행렬 T를 사용하여 새로운 좌표 p를 계산.
# 3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p에서 원래 좌표 p를 복원.

p = np.dot(T,p)
print(p)

reverse_T = np.linalg.inv(T)
p = np.dot(reverse_T, p)
print(p)

[2 6]
[1. 2.]
