In [ ]:
import numpy as np

# Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.
D = np.diag([1, 2, 3])

result = np.array(np.linalg.inv(D))
print(np.dot(D,result))
print(np.linalg.det(D))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
6.0


In [ ]:
# Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.
import random
import numpy as np

up = np.triu(np.random.rand(3,3).reshape(3,3))
print()
down = np.tril(up)
print(down)


[[0.06719728 0.         0.        ]
 [0.         0.03193767 0.        ]
 [0.         0.         0.53492021]]


In [ ]:
# Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.
A = np.array([[4, 7], [2, 6]])

result = np.array(np.linalg.inv(A))
a = np.dot(A,result)
print(np.linalg.det(A))

l = np.eye(3)
print(np.allclose(l, np.linalg.inv(l)))

10.000000000000002
True


In [ ]:
import numpy as np
# Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.
# - 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
# - 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.
X = np.array([1, 2, 3])
para = np.arange(9).reshape(3,3)

Y = X.dot(para)
Y

array([24, 30, 36])

In [ ]:
X = np.array([1, 2, 3])
# 모델 파라미터(bias, w1, w2)
theta = np.array([0.5, 1.5, -2])

# 선형 회귀 모델의 예측값 계산
y_pred = np.dot(X, theta)

print("Input Data Point X =", X)
print("Model Prameters theta = ",theta)
print("PRedicted Value y = ", y_pred)

Input Data Point X = [1 2 3]
Model Prameters theta =  [ 0.5  1.5 -2. ]
PRedicted Value y =  -2.5


#### 행렬곱을 할 때 연산의 순서
연산의 순서는 매우 중요하며, 결과가 달라질 수 있습니다. 주어진 입력과 가중치에 대해 원하는 연산이 무엇인지에 따라 올바른 순서를 선택

np.dot(X,W)와 np.dot(W,X)
- np.dot(X,W)는 X가 (1x3) 벡터이고, W가 (3x3) 행렬이므로, 결과는 (1x3) 벡터입니다.
- np.dot(W,X)는 W가 (3x3) 행렬이고, X가 (3,) 벡터이므로, 결과는 (3,) 벡터입니다.
- 둘 중 어느 것을 선택해야 하는지는 연산의 의미에 따라 결정
  - 입력 벡터 X를 가중치 행렬 W에 곱하여 새로운 출력 벡터를 계산하는 경우
  np.dot(X,W)를 사용.
  - 가중치 행렬 W를 입력 벡터 X에 곱하여 각 출력 뉴런에 대한 값을 계산하는 경우 np.dot(W,X)를 사용.

In [ ]:
# 1x3 3x3 => 1x3
# 3x3 3x1 => 3x1
# 3x1 3x3 => X

In [4]:
import numpy as np

X = np.array([1,2,3])
W = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(np.dot(X,W)) # 1x3 3x3 => 1x3
print(np.dot(W,X)) # 3x3 3x1 => 3x1 numpy가 자동으로 1x3 바꿈.

[30 36 42]
[14 32 50]


In [ ]:
# Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.
# - 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
# - 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

X = np.array([0.5, 1.0, -1.5])
np.random.seed()
W = np.random.rand(3,3)

# 표기순서 W(가중치행렬), X(벡터)
result = W.dot(X)
output = np.dot(W,X)

print(result)
print(output)

print("Input Data Point X =", X)
print("Weight Matrix W = \n",W)
print("Layer Output = ", output)

[ 1.15223129 -0.09013097 -0.72144689]
[ 1.15223129 -0.09013097 -0.72144689]
Input Data Point X = [ 0.5  1.  -1.5]
Weight Matrix W = 
 [[0.60207898 0.92519192 0.04933341]
 [0.97336016 0.88888853 0.97713305]
 [0.56549868 0.05543496 0.70642079]]
Layer Output =  [ 1.15223129 -0.09013097 -0.72144689]


In [6]:
# Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.
# - 1단계: 입력 벡터 X를 정의.
# - 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
# - 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산
# 활성화 함수 적용
X = np.array([1, -2, 3])

np.random.seed()
W = np.random.randn(3,3)
b = np.random.randn(3)
Z = X.dot(W) + b

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(0, x)

output_relu = relu(Z)
output_sigmoid = sigmoid(Z)

print(f'ReLU: {output_relu}')
print(f'시그모이드 : {output_sigmoid}')

ReLU: [4.40233472 0.         1.92653664]
시그모이드 : [0.98789951 0.13061781 0.87286558]


In [ ]:
# Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여 x와 y를 구하세요.
# 3x + 4y = 10
# 2x + y = 5
# 1. 계수 행렬 A와 결과 벡터 b를 정의.
# 2. 행렬 A의 역행렬을 구한다.
# 3. 역행렬을 사용하여 변수 x를 구한다.

A = np.array([[3,4], [2,1]])
b = np.array([10,5])

reverse_A = np.linalg.inv(A)

x = np.dot(reverse_A, b)
print(x)

[2. 1.]


[풀이]
주어진 선형방정식을 행렬 형태로 나타내면 다음과 같다: \\
$A\mathbf{x} = \mathbf{b}$ \\
여기서 \\
$A = \begin{bmatrix}3 & 4 \\2 & 1\end{bmatrix}$,

$\mathbf{x} = \begin{bmatrix}x \\y\end{bmatrix}$,

$\mathbf{b} = \begin{bmatrix}10 \\5\end{bmatrix}$

$\mathbf{x} = A^{-1} \mathbf{b}$

In [7]:
# Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.
# 원래 점의 좌표 p와 변환 행렬 T 정의
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])

# 1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
# 2. 변환 행렬 T를 사용하여 새로운 좌표 p'를 계산.
# 3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p'에서 원래 좌표 p를 복원.

p_ = np.dot(p,T)
print(p_)

reverse_T = np.linalg.inv(T)
p = np.dot(reverse_T, p_)
print(p)

[2 6]
[1. 2.]
