## Numpy Quiz1

Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열 생성

In [119]:
import numpy as np
arr = np.arange(6)
ar1 = arr.reshape(-1,)
ar2 = arr.reshape(2,3)
ar3 = arr.reshape(1,2,3)

print('1차원:\n',ar1)
print('2차원:\n',ar2)
print('3차원:\n',ar3)

1차원:
 [0 1 2 3 4 5]
2차원:
 [[0 1 2]
 [3 4 5]]
3차원:
 [[[0 1 2]
  [3 4 5]]]


Q2. reshape(-1,-1)을 이용 1차원을 2차원, 3차원으로 2차원을 1차원 3차원으로 3차원을 1차원 2차원으로 변환

In [122]:
ar2 = arr.reshape(2,-1)
ar3 = arr.reshape(2,3,-1)
print('2차원:\n',ar2)
print('3차원:\n',ar3)

ar1 = ar2.reshape(-1,)
ar4 = ar2.reshape(3,2,-1)
print('1차원:\n',ar1)
print('3차원:\n',ar4)

ar0 = ar3.reshape(-1,)
ar02 = ar3.reshape(2,3)

print('1차원:\n',ar0)
print('2차원:\n',ar02)

2차원:
 [[0 1 2]
 [3 4 5]]
3차원:
 [[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
1차원:
 [0 1 2 3 4 5]
3차원:
 [[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]
1차원:
 [0 1 2 3 4 5]
2차원:
 [[0 1 2]
 [3 4 5]]


Q3. Q1 1차원 배열을 실수형으로 변환

In [6]:
arr = arr.astype(float)
arr

array([[0., 1., 2.],
       [3., 4., 5.]])

Q4. Q1 1차원 배열의 dtype을 확인

In [7]:
print(arr.dtype)

float64


Q5. 주어진 배열에서 음수 값을 모두 0으로 변경하세요.

arr = np.array([-5, -3, -1, 0, 1, 3, 5])

In [123]:
arr = np.array([-5, -3, -1, 0, 1, 3, 5])
np.where(arr < 0, 0, arr)
# arr[arr < 0] = 0
# arr

array([0, 0, 0, 0, 1, 3, 5])

Q6. 1 ~ 100 까지 배열에서 3의 배수인 것만을 출력

In [125]:
arr = np.arange(1, 101)
arr[arr % 3 == 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Q7. 1 ~ 100 까지 배열에서 5의 배수이면서 2의 배수인 것만을 출력

In [16]:
arr = np.arange(1,101)
result = arr[(arr % 5 == 0) & (arr % 2 == 0)]
result

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Q8. 1 ~ 100 까지 배열에서 3의 배수이거나 5의 배수인 것만을 출력

In [18]:
arr = np.arange(1,101)
result = arr[(arr % 5 == 0) | (arr % 3 == 0)]
result

array([  3,   5,   6,   9,  10,  12,  15,  18,  20,  21,  24,  25,  27,
        30,  33,  35,  36,  39,  40,  42,  45,  48,  50,  51,  54,  55,
        57,  60,  63,  65,  66,  69,  70,  72,  75,  78,  80,  81,  84,
        85,  87,  90,  93,  95,  96,  99, 100])

Q9. 101 ~ 150 사이의 정수를 랜덤하게 추출, 2행 5열 다차원 배열을 생성 후 전치하세요

In [131]:
arr = np.random.randint(101,150, size=(2,5))
arr.T

array([[109, 125],
       [110, 149],
       [146, 109],
       [147, 139],
       [132, 129]])

Q10. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하세요.

In [25]:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Q11. original_array를 1차원 배열로 변환하여 출력하세요.

In [133]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
print(original_array.flatten())

flattened_array = original_array.reshape(-1)
print(flattened_array)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


Q12. 주어진 2차원 배열에서 첫 번째 행을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [136]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
view_arr = original_array[0]
view_arr[0] = 0
print(view_arr,'\n')
print(original_array)

[0 2 3] 

[[0 2 3]
 [4 5 6]]


Q13. 주어진 3차원 배열에서 첫 번째 2차원 배열을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [139]:
original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
view_arr = original_array[0]
view_arr[0] = 0
print(view_arr,'\n')
print(original_array)

[[0 0 0]
 [4 5 6]] 

[[[ 0  0  0]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Q14. 주어진 2차원 배열을 1차원 배열 view로 reshape하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [34]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
view_arr = original_array.reshape(-1)
view_arr[0] = 0
print(view_arr,'\n')
print(original_array)

[0 2 3 4 5 6] 

[[0 2 3]
 [4 5 6]]


Q15. np.ones((10,10))을 아래와 같이 출력하세요.
```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 ```

In [142]:
arr = np.ones((10,10))
arr[1:9,1:9] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Q16. Q. 1 ~ 100을 아래와 같이 출력하세요.

```
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]
 ```

In [144]:
arr = np.arange(1,101).reshape(10,10)
result = []
for i in range(10):
    if i % 2 == 1:
        result.append(arr[i][::-1])
    else:
        result.append(arr[i])
result = np.array(result)
print(result)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


Q17. np.ones((5,5))을 아래와 같이 출력하세요.
```
[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]]
```

In [146]:
arr = np.zeros((10, 10))
arr[2:8, 2:8] = 1
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
z = np.ones((5,5))
np.pad(z, pad_width=2, mode = 'constant', constant_values = 0 ) # pad_width = 상하좌우2칸추가, mode='constant' 패드값 고정, constant_value = 0

Q18. np.arange(4)을 이용해서 아래와 같이 출력하세요.
```
[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0]]
```

In [153]:
np.diag(1+np.arange(4),k=-1) # np.diag 대각선 행렬 생성. 나머지 요소 0 채움

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

Q19. Q. np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)
```
[[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0]]
```

In [156]:
arr = np.zeros((8,8)).astype(int)
arr[0::2, 1::2] = 1
arr[1::2, 0::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [167]:
import numpy as np
pattern = np.array([[0,1],[1,0]])
result = np.tile(pattern,(4,4))
result

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Q20. np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.

In [173]:
arr = np.arange(336).reshape(6,7,8)
# arr
index_arr = np.array([[1,5,4]])
result = arr[[1,5,4]]
print(result)

[[[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[280 281 282 283 284 285 286 287]
  [288 289 290 291 292 293 294 295]
  [296 297 298 299 300 301 302 303]
  [304 305 306 307 308 309 310 311]
  [312 313 314 315 316 317 318 319]
  [320 321 322 323 324 325 326 327]
  [328 329 330 331 332 333 334 335]]

 [[224 225 226 227 228 229 230 231]
  [232 233 234 235 236 237 238 239]
  [240 241 242 243 244 245 246 247]
  [248 249 250 251 252 253 254 255]
  [256 257 258 259 260 261 262 263]
  [264 265 266 267 268 269 270 271]
  [272 273 274 275 276 277 278 279]]]


In [168]:
arr = np.arange(336).reshape(6,7,8)

result = np.unravel_index(100, arr.shape)
print(result)

(1, 5, 4)
